// data.js — Countries dataset for FlagMaster
// Flag images served from flagcdn.com (free, no API key required)
// URL format: https://flagcdn.com/w160/{code}.png

const COUNTRIES = [
  { code: 'gb', name: 'United Kingdom',  continent: 'Europe',   capital: 'London',        fact: 'Home to over 67 million people and the world\'s oldest public railway.' },
  { code: 'us', name: 'United States',   continent: 'Americas', capital: 'Washington D.C.',fact: 'Has the world\'s largest economy and spans 6 time zones.' },
  { code: 'fr', name: 'France',          continent: 'Europe',   capital: 'Paris',          fact: 'The most visited country in the world, welcoming ~90 million tourists a year.' },
  { code: 'de', name: 'Germany',         continent: 'Europe',   capital: 'Berlin',         fact: 'Has over 1,500 different types of beer and more than 1,300 breweries.' },
  { code: 'jp', name: 'Japan',           continent: 'Asia',     capital: 'Tokyo',          fact: 'Has the world\'s oldest company — Kongo Gumi, a construction firm founded in 578 AD.' },
  { code: 'br', name: 'Brazil',          continent: 'Americas', capital: 'Brasília',       fact: 'Home to the Amazon, the world\'s largest tropical rainforest, covering ~60% of the country.' },
  { code: 'in', name: 'India',           continent: 'Asia',     capital: 'New Delhi',      fact: 'Chess was invented in India around the 6th century AD.' },
  { code: 'cn', name: 'China',           continent: 'Asia',     capital: 'Beijing',        fact: 'The Great Wall of China stretches over 21,000 km and took centuries to build.' },
  { code: 'it', name: 'Italy',           continent: 'Europe',   capital: 'Rome',           fact: 'Italy has more UNESCO World Heritage Sites than any other country.' },
  { code: 'es', name: 'Spain',           continent: 'Europe',   capital: 'Madrid',         fact: 'Spain is the second largest country in the EU by area.' },
  { code: 'ca', name: 'Canada',          continent: 'Americas', capital: 'Ottawa',         fact: 'Canada has the longest coastline in the world at over 200,000 km.' },
  { code: 'au', name: 'Australia',       continent: 'Oceania',  capital: 'Canberra',       fact: 'Australia is the only continent that is also a single country.' },
  { code: 'mx', name: 'Mexico',          continent: 'Americas', capital: 'Mexico City',    fact: 'Mexico City is built on the ruins of the ancient Aztec capital, Tenochtitlan.' },
  { code: 'ru', name: 'Russia',          continent: 'Europe',   capital: 'Moscow',         fact: 'Russia spans 11 time zones — the most of any country in the world.' },
  { code: 'za', name: 'South Africa',    continent: 'Africa',   capital: 'Pretoria',       fact: 'South Africa has three capital cities: Pretoria, Cape Town, and Bloemfontein.' },
  { code: 'ng', name: 'Nigeria',         continent: 'Africa',   capital: 'Abuja',          fact: 'Nigeria has the largest population in Africa with over 200 million people.' },
  { code: 'eg', name: 'Egypt',           continent: 'Africa',   capital: 'Cairo',          fact: 'Egypt is home to the only surviving wonder of the ancient world — the Great Pyramid.' },
  { code: 'ke', name: 'Kenya',           continent: 'Africa',   capital: 'Nairobi',        fact: 'Kenya is the birthplace of marathon running — Kenyans have won more Olympic medals in long distance than any nation.' },
  { code: 'ar', name: 'Argentina',       continent: 'Americas', capital: 'Buenos Aires',   fact: 'Argentina is named after silver (argentum in Latin), though little silver was ever found there.' },
  { code: 'se', name: 'Sweden',          continent: 'Europe',   capital: 'Stockholm',      fact: 'Sweden invented the safety match, the zipper, and the adjustable wrench.' },
  { code: 'no', name: 'Norway',          continent: 'Europe',   capital: 'Oslo',           fact: 'Norway has the world\'s longest road tunnel — the Lærdal Tunnel at 24.5 km.' },
  { code: 'nl', name: 'Netherlands',     continent: 'Europe',   capital: 'Amsterdam',      fact: 'The Netherlands has more bicycles than people — roughly 23 million bikes for 17 million citizens.' },
  { code: 'pt', name: 'Portugal',        continent: 'Europe',   capital: 'Lisbon',         fact: 'Portuguese is the 6th most spoken language in the world with ~260 million speakers.' },
  { code: 'pl', name: 'Poland',          continent: 'Europe',   capital: 'Warsaw',         fact: 'Poland is home to the world\'s largest castle by land area — Malbork Castle.' },
  { code: 'tr', name: 'Turkey',          continent: 'Asia',     capital: 'Ankara',         fact: 'Turkey is the world\'s largest producer of hazelnuts, producing ~75% of global supply.' },
  { code: 'sa', name: 'Saudi Arabia',    continent: 'Asia',     capital: 'Riyadh',         fact: 'Saudi Arabia is the largest country in the world with no permanent rivers.' },
  { code: 'kr', name: 'South Korea',     continent: 'Asia',     capital: 'Seoul',          fact: 'South Korea has the fastest average internet connection speed in the world.' },
  { code: 'id', name: 'Indonesia',       continent: 'Asia',     capital: 'Jakarta',        fact: 'Indonesia is the world\'s largest archipelago, consisting of over 17,000 islands.' },
  { code: 'th', name: 'Thailand',        continent: 'Asia',     capital: 'Bangkok',        fact: 'Thailand is the only Southeast Asian country never to have been colonised by a European power.' },
  { code: 'gr', name: 'Greece',          continent: 'Europe',   capital: 'Athens',         fact: 'Greece has more archaeological museums than any other country in the world.' },
  { code: 'ch', name: 'Switzerland',     continent: 'Europe',   capital: 'Bern',           fact: 'Switzerland has four official languages: German, French, Italian, and Romansh.' },
  { code: 'be', name: 'Belgium',         continent: 'Europe',   capital: 'Brussels',       fact: 'Belgium produces over 220,000 tonnes of chocolate per year.' },
  { code: 'nz', name: 'New Zealand',     continent: 'Oceania',  capital: 'Wellington',     fact: 'New Zealand was the first country to give women the right to vote in 1893.' },
  { code: 'cl', name: 'Chile',           continent: 'Americas', capital: 'Santiago',       fact: 'Chile is the longest country in the world, stretching 4,300 km from north to south.' },
  { code: 'gh', name: 'Ghana',           continent: 'Africa',   capital: 'Accra',          fact: 'Ghana was the first sub-Saharan African country to gain independence from colonial rule, in 1957.' },
  { code: 'ma', name: 'Morocco',         continent: 'Africa',   capital: 'Rabat',          fact: 'Morocco\'s Fes el-Bali is the world\'s largest car-free urban area.' },
  { code: 'dk', name: 'Denmark',         continent: 'Europe',   capital: 'Copenhagen',     fact: 'Denmark consistently ranks as one of the happiest countries in the world.' },
  { code: 'at', name: 'Austria',         continent: 'Europe',   capital: 'Vienna',         fact: 'Vienna was home to Beethoven, Mozart, Schubert, and Brahms at various points in history.' },
];
